### ISSUE TITLE
Arrow does not accept YYYYMMDDTHHmmss formatted dates

### ISSUE THREAD

**Issue by Ni-Knight** [C4ptainCrunch/ics.py#104]
File "/usr/local/lib/python2.7/dist-packages/arrow/parser.py", line 267, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of [u'YYYY-MM-DDTHH:mm'] on '20170606T140752Z'

Seems like the format 'YYYYMMDDTHHmmss' should be added to utility.py at lines 46 and 50:
```
def iso_to_arrow(time_container, available_tz={}):
    if time_container is None:
        return None

    # TODO : raise if not iso date
    tz_list = time_container.params.get('TZID')
    # TODO : raise if len(tz_list) > 1 or if tz is not a valid tz
    # TODO : see if timezone is registered as a VTIMEZONE
    if tz_list and len(tz_list) > 0:
        tz = tz_list[0]
    else:
        tz = None
    if ('T' not in time_container.value) and \
            'DATE' in time_container.params.get('VALUE', []):
        val = time_container.value + 'T0000'
    else:
        val = time_container.value

    if tz and not (val[-1].upper() == 'Z'):
        naive = arrow.get(val, 'YYYYMMDDTHHmmss').naive
        selected_tz = available_tz.get(tz, 'UTC')
        return arrow.get(naive, selected_tz)
    else:
        return arrow.get(val, 'YYYYMMDDTHHmmss')
```

That seems to solve it.

**Comment by srwhite** [comment]
The suggested fix seems to work for me. New arrow has a lot of useful functions like 'shift', so it would be nice to be able to upgrade without breaking ics.

**Comment by C4ptainCrunch** [comment]
The fix breaks the tests unfortunately :/ All dates are not YYYYMMDDTHHmmss. We have at least some YYYYMMDD and maybe more.

**Comment by sovietnorm** [comment]
So in the [Arrow arrow.api docs](https://arrow.readthedocs.io/en/latest/#module-arrow.api) there's a feature of arrow.get where you can specify multiple formats. (try ctrl-f list of formats)

Since [RFC5445](https://tools.ietf.org/html/rfc5545#section-3.3.5) and [RFC2445](https://tools.ietf.org/html/rfc2445#section-4.3.5) are pretty specific about what a date can and cannot look like, you should be able to safely provide a list of acceptable formats.

It would also be pretty reasonable (but ugly) to have a few try-except blocks to see if arrow accepts one of the standards, and failing that, letting it try with just a raw get.

If I get time (ha ha) I'll submit a patch with what that might look like, but I have to put together what some of the format strings might look like, but you can honestly probably do that faster than I can @C4ptainCrunch

**Comment by N-Coder** [comment]
Seems like this is already long fixed, as the problematic format is included in the [list of available formats](https://github.com/C4ptainCrunch/ics.py/blob/12dcd62bc4a9fd41bb883dd04c6baf963563b5e5/ics/utils.py#L30). If I'm mistaken, please comment here (or open a new issue) and provide an example that doesn't work, and I'll try to fix it.
