### ISSUE TITLE
Support extensions/custom fields

### ISSUE THREAD

**Issue by albertvaka** [C4ptainCrunch/ics.py#171]
Adding non-standard fields to a calendar object is not supported. However, some non-standard fields like 'X-WR-CALNAME' (the display name of a calendar) are really common in ics files. It would be nice to have a dict where we can add any fields we want, and that they get serialized/unserialized to/from ics.

See: https://en.wikipedia.org/wiki/ICalendar#Calendar_extensions

**Comment by C4ptainCrunch** [comment]
Actually, there is already a way to do this, it's just (unfortunately) undocumented
```pycon
>>> import ics                                                                                                                                                                          

>>> event = ics.Event()                                                                                                                                                                 
>>> content_line = ics.parse.ContentLine(name='X-WR-CALNAME', params={}, value='mycalendarname')                                                                                       
>>> event._unused.append(content_line)
>>> print(str(event))
                                                                                                                                                                  
BEGIN:VEVENT
X-WR-CALNAME:mycalendarname
...
END:VEVENT
```

It also goes the other way around : unknown fields or objects (either because we don't support 100% of the RFC or because they are custom) encountered while parsing the calendar also end up in `._unused`

I guess this should be better documented (and maybe `._unused` should be renamed to something more public, like `.extra` ?)

**Comment by zuphilip** [comment]
The `X-WR-CALNAME` is a property of a Calendar and not Event, but the same idea seem to work there.
