### ISSUE TITLE
ParseError if emojis/unicode in description/text

### ISSUE THREAD

**Issue by Bouni** [C4ptainCrunch/ics.py#206]
I try to load a shared calendar from a Nextcloud instance via requests.
One of the calendar entries has emojis in the description, ics throws an exception when it comes accross the first emoji:

The error:
```
tatsu.exceptions.FailedToken: (1:27) expecting '\r\n' :
DESCRIPTION:Hallo zusammen😊\n\nEndlich Ist es soweit....🙃😎😁\n\n
                          ^
CRLF
contentline
start

During handling of the above exception, another exception occurred:

File "/usr/lib/python3.7/site-packages/ics/grammar/parse.py", line 78, in parse
    raise ParseError()
ics.grammar.parse.ParseError
``` 

The section of the ical:
```
BEGIN:VEVENT
CREATED:20190422T210447
DTSTAMP:20190422T210447
LAST-MODIFIED:20190422T210447
UID:NTG0P2GYEMBOTMH04Z4OP
SUMMARY:Party bei <redacted>
CLASS:PUBLIC
DESCRIPTION:Hallo zusammen😊\n\nEndlich Ist es soweit....🙃😎😁\n\n
STATUS:CONFIRMED
DTSTART;TZID=Europe/Berlin:20190601T140000
DTEND;TZID=Europe/Berlin:20190601T235500
END:VEVENT
```

**Comment by C4ptainCrunch** [comment]
This is interesting :thinking: 
I'll have to check if emojis are supported by the RFC

**Comment by Bouni** [comment]
Nextcloud handles them without any trouble :man_shrugging:

**Comment by anirbanmu** [comment]
I just hit this one as well:

```
tatsu.exceptions.FailedToken: (1:24) expecting '\r\n' :
SUMMARY:New York ePrix 🇺🇸
```

**Comment by roman76aut** [comment]
Found this not working in 0.6 but works if I use 0.5 ... so looks like a regression

**Comment by C4ptainCrunch** [comment]
This is indeed, a regression, the parser grammar for QSAFE_CHAR, SAFE_CHAR and VALUE_CHAR is too restrictive and rejects valid unicode chars.

**Comment by Azhrei** [comment]
> This is indeed, a regression, the parser grammar for QSAFE_CHAR, SAFE_CHAR and VALUE_CHAR is too restrictive and rejects valid unicode chars.

Has there been any forward movement on your end, then?

(Continued from my duplicate at #211 )

> I did notice that the tatsu parser uses Python's built in `re` module unless `regex` is available. Given that the `re` module has a number of deficiencies, I'll try installing `regex` and have another go at it.

This didn't help.  The built in `re` doesn't support some RE constructs that are possible/popular in Perl and Java, for example.

I did find that the smiley emoji is U+1F642 and that doesn't fit in a 16-bit word, but I thought Python used a 32-bit word (an assumption on my part based on hearsay).  I'll be researching this more when I have time.

**Comment by C4ptainCrunch** [comment]
> Has there been any forward movement on your end, then?

Not yet. Personally, i don't have a lot of free time at the moment to work on ics.py and others contributors are busy fixing other bugs at the moment. But this is definitely something that we have quite high in our todolist

**Comment by Azhrei** [comment]
Okay, thanks for the status update.  Yeah, RL can be such a bummer when it gets in the way of fun! 😉

**Comment by N-Coder** [comment]
The [definition of the rules](https://github.com/C4ptainCrunch/ics.py/blob/master/ics/grammar/contentline.ebnf) says:
```
QSAFE_CHAR    = ?"[ \x21\x23-\x7E\u0080-\uffff]";
QSAFE_CHAR_STAR    = ?"[ \x21\x23-\x7E\u0080-\uffff]*";
SAFE_CHAR     = ?"[ \x21\x23-\x2B\x2D-\x39\x3C-\x7E\u0080-\uffff]" ;
SAFE_CHAR_STAR     = ?"[ \x21\x23-\x2B\x2D-\x39\x3C-\x7E\u0080-\uffff]*" ;
VALUE_CHAR    = ?"[ \x21-\x7E\u0080-\uffff]";
VALUE_CHAR_STAR    = ?"[ \x21-\x7E\u0080-\uffff]*";
```
The most restrictive regex here seems to be `[ \x21\x23-\x2B\x2D-\x39\x3C-\x7E\u0080-\uffff]`, with the other ones only allowing further characters. The related RFC section is [here](https://www.kanzaki.com/docs/ical/text.html).
Maybe we should work with excluding the disallowed characters instead of trying to think of all allowed characters?
[Analyzing the regex](//regexr.com/4u4rj) (note that the website itself seems to have problems with emojis in the example data and the result also changes depending on whether you are using PCRE or JavaScript and whether the unicode option is enabled), the following characters seem to be excluded:
[`\x00-\x19, \x22, \x2C, \x3A, \x3B, \x7F`](//regexr.com/4u4sq):

- `\x00-\x19` Range. Matches a character in the range NULL to EM (char code 0 to 25). Case sensitive.
- `\x22` Escaped character. Matches a `"` character (char code 34).
- `\x2C` Escaped character. Matches a `,` character (char code 44).
- `\x3A` Escaped character. Matches a `:` character (char code 58).
- `\x3B` Escaped character. Matches a `;` character (char code 59).
- `\x7F` Escaped character. Matches a DEL character (char code 127).

`VALUE_CHAR` thus only excludes non-printable characters (which might also be influencing #219), `QSAFE_CHAR` additionally excludes a quote. I'll try to put some more thoughts why it works this way (why the excluded comma?) and whether we can safely change the regex to fix this or whether TatSu/the Regex Engine has some options to make this work.

**Comment by Azhrei** [comment]
I believe what you're proposing is what I tried.  See #211 for a description (mentioned above).  If so, just switching to an "exclude instead of include" approach didn't work for me.  Although if you see a mistake in my calculation of what the reversed RE should be, I'd be thrilled to be shown wrong! 😉

There may be something else in the Tatsu parser that has problems with Unicode chars > 0xFFFF as well, but after digging into the code a little bit, I got lost and gave up. 🙁

**Comment by N-Coder** [comment]
Oh thanks, very nice! Should have thoroughly read you other issue. :see_no_evil: 
Your changes did work for me, see the [notebook](https://gist.github.com/N-Coder/78e4c8789fe1b579b329ce6bce262ad8) here. The inverted regex fixed the parsing of emojis, but still doesn't accept an embedded newline (which is why I removed them from the examples in the notebook).
I guess that we could include your fix for emojis to resolve this issue and later take a more indepth look at embedded newlines and linefolding in conjunction with issue #210/#215.

**Comment by Azhrei** [comment]
Interesting, thanks.  I’m on my phone, but I’ll look at your nb when I’m back on my laptop.  Maybe the difference in results is the version of Python being used...?  (In terms of why it didn’t work for me using the Tatsu parser.)

In any case, that’s on my end, and since it works for you (and your nb) in _can_ work for me.  Thanks again!
