### ISSUE TITLE
Support of extra attributes in event

### ISSUE THREAD

**Issue by GMLudo** [C4ptainCrunch/ics.py#78]
Hi,

Unfortunately to me, if Google Calendar supports TRANSP attribute, with Office 365, they use extra attributes to do that:

```
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
```

However, they provide more information.

Do you have an suggestion to implement that ?
I thought to add an attribute "extra", with a dict of extra attributes.

Thanks for your time.

**Comment by davidjb** [comment]
+1 for this to be built in, but it's easy enough to add yourself:

```
from ics import Event
from ics.parse import ContentLine

@Event._outputs
def o_properties(event, container):
    """ Workaround for arbitrary properties on Events.
    """
    if hasattr(event, 'properties') and event.properties:
        for key, value in event.properties:
            container.append(ContentLine(key, value=value))

# ... later on ...
event = Event()
event.properties = (
   ('X-MICROSOFT-CDO-APPT-SEQUENCE, '0')
   ('X-MICROSOFT-CDO-BUSYSTATUS': 'FREE')
   # ...your other properties here...
)
print(event)
```

I'll probably wrap this up into a pull request at some point, but this works.  The ``Event._outputs`` decorator adds the function into the Event._OUTPUTS list of functions so will be run on string coercion.

**Comment by C4ptainCrunch** [comment]
Honestly, i don't know how to deal with non-standard properties.
For now, i think i'm going to ignore properties that not match with official ones because they can not be outputted in a standard way.

Right now, unknown properties are stored in a `._unused` field on the `Calendar` and `Event` objects but they are not easily accessible. I'll experiment with a `.extra`  field to see how it improves the API.

**Comment by C4ptainCrunch** [comment]
see #171
